[package]
name = "cocoon"
version = "0.1.0"
description = "Simple secure container with strong encryption and format validation."
authors = ["Alexander Fadeev <fadeevab.com@gmail.com>"]
edition = "2018"
license = "MIT"
keywords = ["secure", "storage", "keystore", "wrapper", "container"]
categories = ["encoding", "cryptography"]
homepage = "https://github.com/fadeevab/cocoon"
repository = "https://github.com/fadeevab/cocoon"
documentation = "https://docs.rs/cocoon"
readme = "README.md"

[dependencies]
